version: '3'

networks:
  productive:


services:
  nginx:
    image: nginx:stable-alpine
    container_name: productive-nginx
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - productive

  mysql:
    image: mysql:5.7.29
    container_name: productive-mysql
    restart: unless-stopped
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3307:3307"
    environment:
      - MYSQL_DATABASE=productive_db
      - MYSQL_USER=kansai
      - MYSQL_PASSWORD=adygcy8b
      - MYSQL_ROOT_PASSWORD=adygcy8b
      - SERVICE_TAG=dev
      - SERVICE_NAME=mysql
    networks:
      - productive

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: productive-phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: kansai
      PMA_PASSWORD: adygcy8b
    volumes:
      - ./upload.ini:/usr/local/etc/php/php.ini
    ports:
      - "8888:80"
    networks:
      - productive

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: productive-php
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - productive

  composer:
    image: composer:latest
    container_name: productive-composer
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    networks:
      - productive

  artisan:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: productive-artisan
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
    working_dir: /var/www/html
    entrypoint: [ 'php','/var/www/html/artisan' ]
    networks:
      - productive
















